### ISSUE TITLE
Multiple Requests

### ISSUE THREAD

**Issue by ghost** [flouthoc/minAjax.js#13]
**Because this library used an object to register an AJAX request, what happens if there are more than one request?** It may clog up the script. Unfortunately, I am not able to find the answer myself without doing several things, because I try to make my code all client-side and I only have one RPi that's in use. Anyhow, this raises two questions in my mind:

1. Should this whole repo be based around a function with multiple parameters instead of an object with properties?

2. If we continue to leave it as an object, would it be possible if we made a loop that goes through all the AJAX requests _as an array_, making the syntax for properties like `config[i].method` (for example)?

**Comment by ghost** [comment]
Another possible data type is classes. This way every AJAX request can be ran through a constructor or something of the sort.

**Comment by flouthoc** [comment]
@ForgivenNin Hey , thanks a lot for the feedback. I believe the idea it to keep the core ajax method as simple as possible so things like making multiple ajax requests should be handled by the implementer. Right method should be to create a array of minajax object by the implementer but we can definitely consider this as future enhancement.

**Comment by ForgivenNin** [comment]
What do you mean by the "implementer"?


Which way of doing this do you think would be the most simple (both in file size and in application)?
To me, here's what seems the most minimalist in rank: _1st: Function --- 2nd: Object --- 3rd: Class_.

**Comment by ghost** [comment]
In using this script in [another repo](https://github.com/ForgivenNin/singl-page)(thanks 😄), I saw that the object was wrapped in parentheses like a function. Maybe this is what you were talking about; because if so, that completely slipped past me.

What did you mean by the "implementer"?
