### ISSUE TITLE
Retrieving Data

### ISSUE THREAD

**Issue by ghost** [flouthoc/minAjax.js#15]
On my pull request, I added a JSON feature, but I saw in the object syntax, there's the data attribute. However, that's only for sending. Is there something that the user has to set to specify the data from the XML/JSON? Like if I wanted to get/parse the data from this `.json` file.

`{`
`  "txt": "This is an example of using JSON!"`
`}`

It may be easier to answer if there's only one string or data type, but when there's more the request will have to be more detailed.

**Comment by flouthoc** [comment]
minAjax accepts the JSON as the default object  , however you can parse XML and convert it to JSON before invoking minAjax. Idea is to keep library as minimal as possible. I hope this answers your question.

**Comment by ghost** [comment]
Okay, I see. I could go ahead and make that clear on my (or the) `README`.
Before I close the issue and do that, though, did that require anything to make it accept JSON by default? Because as far as I know, the `parse()` is what actually makes it usable in a script.
